### ISSUE TITLE
zset view should display scores in sorted order

### ISSUE THREAD

**Issue by dmk23** [marians/rebrow#1]
First wanted to thank you for making this project. A tool which allows quick-and-dirty inspection of Redis contents by typing URLs into browser is way overdue.

However, right now the sorted set view does not show the scores. That pretty much defeats the purpose of sorted sets whose whole point is to use these scores for indexing

I made a local fix to display scores (descending order) by replacing zrange line in runserver.py with this:

```
        val = r.zrange(key, 0, -1, withscores=True, desc=True)
```

However it would be nice to make this a supported feature in the project - in particular with some sort of a 3-column template for rank, score and value displayed separately

**Comment by marians** [comment]
Great to hear that rebrow is of use to someone.

Feel free to send a pull request if you happen to implement this.

**Comment by marians** [comment]
#9 contains a fix for this. I implemented the ascending order. In the end, I guess the "right" order depends on the use case of the data.

Thanks for suggesting this!
